# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
