# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 10:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmerprofile',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
