# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_sendquotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendquotes',
            old_name='number',
            new_name='phone_number',
        ),
    ]
