# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170722_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='user_name',
            field=models.CharField(default='mike', max_length=10),
        ),
    ]
