# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170724_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendquotes',
            old_name='address',
            new_name='delivery_address',
        ),
    ]
